# Generated by patch: refactor button styles to share a common base
_BTN_BASE = {
    # Kivy props
    "background_normal": "",
    "background_down": "",
    "background_color": (0, 0, 0, 0),
    "markup": True,
    # shared "css-like" props
    "border-radius": 10,
    "hover-edge-color": "#63df82",
}

_EXCHANGE = {
    "background": "rgba(0,0,0,0)",
    "padding": 8,
    "spacing": 6,
}

STYLES = {
    # --- Buttons ---
    "btn_menu": {
        **_BTN_BASE,
        "edge-width": 0.1,
        "edge-color": "#7fad7f",
        "background": "rgba(0,0,0,0)",
        "hover-background": "#14241c",
        "padding": 8,
        "spacing": 6,
    },
    "btn": {
        **_BTN_BASE,
        "edge-width": 1,
        "edge-color": "#233a2f",
        "background": "#14241c",
        "hover-background": "#2a4a3b",
        "padding": 10,
        "spacing": 8,
    },

    "connection": {
        "padding": 8,
        "spacing": 6,
    },

    "exchange_block": {
        "background": "#1C2029",
        "padding": 8,
        "border-radius": 10,
        "edge-color": "#233a2f",
        "hover-background": "#252A36"
    },

    "exchange_connection": {
        **_EXCHANGE,
        "color": "#54C039",
    },

    "exchange_disconnection": {
        **_EXCHANGE,
        "color": "#C03939",
    },

    # --- Overlay scrim ---
    "scrim": {
        "background_color": "#0000007F",
        "anim": {
            # Анімуємо лише властивості, які мають змінюватись
            "open":  {"opacity": 1.0 },
            "close": {"opacity": 0.0 }
        }
    },
    # --- Top bar ---
    "topbar": {
        "background": "#0e1419",
        "padding": 8,
        "spacing": 8,
        "edge-width": 0,
    },
    # --- Sliding dashboard (left panel) ---
    "dashboard": {
        "background": "#101318",
        "edge-color": "#0b0e11",
        "edge-width": 1,
        "border-radius": 0,
        # Edge shadow (soft)
        "edge-shadow": {"side": "right", "size": 48, "color": "rgba(0,0,0,0.60)", "steps": 12},
        # Animation: open/close
        "anim": {
            "duration": 0.25,
            "transition": "out_quad",
            "open": {
                "x": 0,
                "edge_shadow_opacity": 1.0
            },
            "close": {
                "x": -300,
                "edge_shadow_opacity": 0.0
            }
        }
    },
    # --- Content block/card ---
    "block": {
        "background": "#1A1F27",
        "hover-background": "#1A1F27",
        "border-radius": 12,
        "edge-color": "#101318",
        "edge-width": 1,
        "padding": 12,
        "spacing": 8,
    },

    "grid_block_balances": {
        "background": "#29323F",
        "border-radius": 12,
        "edge-color": "#101318",
        "edge-width": 1,
        "padding": 12,
        "spacing": 8,
    },

    "name_table_balances": {
        "color": "#60C700",
        # "font-size": 15
    },

    "active_value_table_balances": {
        # "color": "#6B3030",
        "color": "#B3C700",
    },

    "deactivated_value_table_balances": {
        "color": "#6B3030"
    },

    "BUY_history_style":{
        "color": "#60C700"
    },

    "SELL_history_style": {
        "color": "#9C0909"
    },

    "btn_analysis": {
        **_BTN_BASE,
        "background": "#302542DF",
        "hover-background": "#3C2053"
    }
}
